### ISSUE TITLE
Option to hide new alarm in main menu

### ISSUE THREAD

**Issue by Titintgn** [Tertiush/Alarmin-Android-App#17]
In options, option  hide menu new alarm in main menu

**Comment by Tertiush** [comment]
You will have to explain better, and give a use-case please.

**Comment by Titintgn** [comment]
In the main menu appears where alarms have the option to add new alarm (añadir nueva alarma...). That option you can hide. In previous versions only ran in set alarms (google translate ;))

**Comment by Tertiush** [comment]
Ok cool I understand, perhaps I will only show it when there's no alarm configured

**Comment by Titintgn** [comment]
That would be even better jjeje

**Comment by Tertiush** [comment]
Implemented in next release
