### ISSUE TITLE
cannot read property 'split'

### ISSUE THREAD

**Issue by grapedrank** [Tertiush/Alarmin-Android-App#21]
when i try connect i get an incorrect pin/password error followed by (Internal error: Cannot read property 'split' of undifined)... i have confirmed both pin and password are correct

**Comment by Tertiush** [comment]
Please send me a log file after attempting to connect:

1. Go to settings and choose 'verbose' log mode
2. Restart the app (complete exit, open again)
3. Try to connect again to reproduce the error
4. Open the menu and go into 'view logs'
5. At the bottom click on the feedback button and email me the log. I will reply here on github. thanks

cheers

**Comment by grapedrank** [comment]
i tried a different password on the panel and now it connects fine...
my old password contained special characters. could a "/" have caused this? maybe an un-sanitized input?

**Comment by Tertiush** [comment]
I dont think so. Please drop me a mail with a password similar to yours (just want to replicate the special characters and length). rashoftapps at gmail dot com
