### ISSUE TITLE
Video Feed

### ISSUE THREAD

**Issue by Aldogre** [Tertiush/Alarmin-Android-App#29]
Hello..any plans to add video feed (HD77/HD78) on EVO digiplex EVO?

**Comment by Tertiush** [comment]
Hi. Unfortunately not as I don't own any of these units. Do you perhaps know if they expose the video feed through some url? Any info you have will be helpful in determining if it's possible and worth the effort. Thanks!

**Comment by Aldogre** [comment]
I'm not that much aware - I'm having a lot of troubles to connect with the paradox insight app myself whereas your app works a charm. 

All I know that the app connects directly to the camera and uses port 5005.  I can make one available if you are looking for a unit to play with.

**Comment by Tertiush** [comment]
That will be great yes. I can only have a look sometime tomorrow to later
in the week. You can drop me the details at: Rashoftapps at gmail.com

Thanks!

**Comment by Tertiush** [comment]
Unfortunately this is not possible as it appears as if Paradox has implemented some custom encryption on the link, making it impossible for me to integrate with.
