### ISSUE TITLE
Notification wording

### ISSUE THREAD

**Issue by Prodigalza** [Tertiush/Alarmin-Android-App#31]
I'm using an Evo192 panel with TM50 keypads. 
Whether I arm by STAY when going to sleep or ARM with exit delay when leaving the house, I get the same notification wording, "By: Quick Stay/Instant"
So, when I'm not the one at home, I don't actually know if the person at home has gone to bed or gone out. For example when I have a house sitter looking after my place. 

Any way to alter the notification wording to be more descriptive/accurate? 

Thanks

**Comment by Tertiush** [comment]
Hi

Sorry for the late reply. The wording of notifications come directly from the IP module. The backend server that sends the notifications simply takes the IP module's emailed notifications and sends it as a push notification. There is thus no way for me to determine whether an stay of arm was used.
