### ISSUE TITLE
PMH id cannot contain "-"

### ISSUE THREAD

**Issue by lperez31** [Tertiush/Alarmin-Android-App#36]
When there are some specific chars like "-" in PMH id, the app does not accept the id. For instance, the id "My-Paradox-Id" is considered as invalid by the app.

**Comment by Tertiush** [comment]
Thanks for letting me know, I'll have a look at it. I'm planning a release soon, to add a few push notification sounds and IFTTT integration (currently in beta release). Will try to get this fixed before the general release.

**Comment by Tertiush** [comment]
Fixed in latest release
