### ISSUE TITLE
Panic Button

### ISSUE THREAD

**Issue by AZtech25276** [Tertiush/Alarmin-Android-App#37]
Tertius, have you thought of building in the functionality of a panic button in the app? It could mirror that used in the panels configuration, as if a keypad panic was pushed? Maybe even put the panic on the home screen?

**Comment by Tertiush** [comment]
I haven't seen this function in the IP150's web interface, which is mainly used by Alarmin to control the alarm. If paradox adds this functionality in the future, I will add it to the app. But for now there's not much I can do. cheers
