### ISSUE TITLE
Can't activate ByPass service

### ISSUE THREAD

**Issue by ErlandasParadox** [Tertiush/Alarmin-Android-App#40]
The App works great, but only one problem that I can not activate ByPass service. The connection to module starts and do not finish... I have found the same already closed issue, but could not find any detailes how it was fixed. Pls. HELP.

**Comment by ycp78** [comment]
I am having the same issue.
When select bypass button of a zone, a message displays: "connecting to port software" an endless circle appears, it never connects to port software and it is impossible to bypass a zone. EVO 192 fw 3.2; IP150 v.4.00. 
Please check. 
Thanks in advance.

**Comment by ErlandasParadox** [comment]
Thanks, YCP78, sharing the same issue! Hope that will help us both to get any info from Apps producer how it can be fixed.

**Comment by Tertiush** [comment]
Hi guys, yes sorry for the delay....

I already see that V4 of the ip modules firmware is involved, there's a
known issue with this which I am unable to resolve, not sure what Paradox
implemented with that release....

@ErlandasParadox what version is your ip module?

**Comment by ErlandasParadox** [comment]
IP150 firmawe version 1.39.02
EWO 192 firware version 4.52

**Comment by ycp78** [comment]
@ErlandasParadox and @Tertiush. Thanks for your answers. Confirmed was not an isolated case.

Do you know if there is a way, other than keyboard, to remotely bypass a zone for EVO 192?

Thanks and regards.

**Comment by ErlandasParadox** [comment]
I know only this way - bypass zones using paradox keyboard. But with paradox app I can do that without any problem. Also I can connect to Paradox EVO, IP 150 and setup/manage them via Chrome/explorer without any problems... also Babycare soft works well...

**Comment by Tertiush** [comment]
@ErlandasParadox your IP module should allow bypassing (if memory serves me correctly now). Please send me a log from within the app, directly to my dev email account. Please follow the instruction on the top of the logs screen. I'll get back to you.

**Comment by ycp78** [comment]
@ErlandasParadox Thanks a lot.

**Comment by ErlandasParadox** [comment]
Dear Tertiush, I have sent you a log already. Pls. find it in your mail inbox. Thanks.

**Comment by ErlandasParadox** [comment]
The change you have made did not give an expected improve - bypass function does not works. I have sent to you another log which I made with your new version of app.

**Comment by Tertiush** [comment]
Ok, I didn't receive the new log. Please resend it thanks

**Comment by ErlandasParadox** [comment]
Dear Tertiush. I have sent new log within an app. Pls. find it.

Thanks.

2017 rgp. 2 20:07 "Tertius" <notifications@github.com> rašė:

**Comment by Tertiush** [comment]
Fixed, release being rolled out in stages
