### ISSUE TITLE
System Failure push

### ISSUE THREAD

**Issue by provaprova1** [Tertiush/Alarmin-Android-App#41]
I would like to have a push notification when there's a system failure (f.e. when electric line is down). The app recognizes correctly the failure. I would like to have a push notification for it. 
Thank you very much

**Comment by Tertiush** [comment]
All available notifications supported by Paradox are selectable from within the push menu in the app (after connecting to the alarm). Unfortunately if the one you are after is not included in any of the ones there then that's a limitation on Paradox's side.

**Comment by Tertiush** [comment]
Ok, when you say "even when selected from the alarm menu", which exact
options are you referring to? My app does not generate the notifications,
it simply passes them from the alarm panel to your phone. If the alarm
panel doesn't generate an email message, my server won't send any push
notification. So unfortunately this appears to be out of my hands.

**Comment by provaprova1** [comment]
This is the option selected in the app menu (GUASTI which means troubles)

![image](https://user-images.githubusercontent.com/31503604/29929698-7567e3d8-8e6c-11e7-9dba-c2393604df96.png)

This is the failure correctly recognized by the app

![image](https://user-images.githubusercontent.com/31503604/29929815-d7b59116-8e6c-11e7-9fec-a296de23a5f7.png)

![image](https://user-images.githubusercontent.com/31503604/29929830-e685867e-8e6c-11e7-9381-1975c631e12d.png)

and, if it helps, this is the notification from the original app

![image](https://user-images.githubusercontent.com/31503604/29929873-10d747fa-8e6d-11e7-879b-2ea972716a34.png)

**Comment by Tertiush** [comment]
If you selected the troubles notifications and not receiving the one your after then it's a limitation of the ip module, not the app. The push notifications only work with the emails that's the ip module can send. If you don't receive a push notification the that type of event is not reported in this way. It's only listed as a trouble and not emailed. Theres unfortunately nothing I can do about this.
