### ISSUE TITLE
Push notifications stopped working

### ISSUE THREAD

**Issue by coderars** [Tertiush/Alarmin-Android-App#48]
Hi @Tertiush ! First of all a big thank you for this great app providing us for free! I've been using the app since months with no problem. Push notifications were working flawlessly on 2 separate phones. However since a few weeks push notifications stopped working. I've tried everything to make it work again with no success. My steps were (test arm/disarm each after):

- Change something in the IP150 configuration to have it restarted
- Tested my ISP's smtp settings in the "Email configuration" menu and I've got the test mail immediately (Unfortunately my ISP blocks every mail sent out that not were sent via their own smtp server, so I can't use the default google smpt, but it was working ok before...)
- Disable then re-enable push notifications in the app's settings
- Uninstalled then reinstalled the whole app from the Play store and configure everything again
- Push history is empty...
- In the app, "Push service: Online" is ok. Always.

I think I can understand the whole push process, app settings, IP module configuration, all was OK before but now I'm unable to get it work... Maybe my ISP is blocking the outgoing email sent to *@alarmin.servebeer.com? Any idea?

I've sent you an email from the app's feedback menu with some logs.
Thanks!

**Comment by Pablodina** [comment]
Hi Tertiush,
Thanks for the excellent App.
A week ago, the PUSH stopped working and it does not send me the emails as before.
I tried several things and I could not solve it.
Any ideas? Thank you!

**Comment by Tertiush** [comment]
Hi.

What does the logs say in your ip module? Any "failed sending email"
entries?

**Comment by Tertiush** [comment]
Hi also use the Alarmin SMTP server in my setup and it works flawlessly. Using any other SMTP server opens you up to their policies around emails.... Either way, we did experience some downtime about a month ago which probably caused the "always disconnects at TCP level" error on 12 July. I would suggest you contact your ISP to unblock the domain.

**Comment by coderars** [comment]
Thank you! I'll contact my ISP about this. Now overridden my SMTP settings from the Alarmin app and push is working again with your SMTP on that custom port. However in my old config for double security I was using my private email on "Address 01" for the alarm event. Now it says: "Use_own_SMTP_server_before@editing.com". I can understand why, so later I need to switch back to my old settings when the unblock is done. Thank you again and sorry for the false issue.

**Comment by Tertiush** [comment]
No worries - good luck
